version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /

    # Group packages into shared PR
    groups:
      application:
        patterns:
          - '@open-iframe-resizer/*'
          - 'accessible-autocomplete'
          - 'axios'
          - 'basic-auth'
          - 'cheerio'
          - 'clipboard'
          - 'compression'
          - 'express'
          - 'gray-matter'
          - 'helmet'
          - 'highlight.js'
          - 'js-beautify'
          - 'lunr'
          - 'marked'
          - 'nhsuk-frontend'
          - 'nunjucks'

      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'caniuse-lite'
          - 'cssnano'
          - 'cssnano-*'
          - '*-loader'
          - 'postcss'
          - 'postcss-*'
          - 'sass-embedded'
          - 'webpack'
          - 'webpack-*'
          - '*-webpack-plugin'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'

      test:
        patterns:
          - 'jest'
          - 'jest-*'

      tools:
        patterns:
          - 'browser-sync'
          - 'concurrently'
          - 'del-cli'
          - 'husky'

    schedule:
      interval: monthly

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

      # Include indirect browser data updates
      # https://caniuse.com
      - dependency-name: caniuse-lite

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directories:
      - .github/workflows/

    schedule:
      interval: 'monthly'
