version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /

    # Group packages into shared PR
    groups:
      application:
        patterns:
          - '@open-iframe-resizer/*'
          - '@prettier/*'
          - 'accessible-autocomplete'
          - 'axios'
          - 'basic-auth'
          - 'cheerio'
          - 'compression'
          - 'express'
          - 'gray-matter'
          - 'helmet'
          - 'highlight.js'
          - 'js-beautify'
          - 'lunr'
          - 'marked'
          - 'nhsuk-frontend'
          - 'nunjucks'
          - 'outdent'
          - 'slug'

      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-plugin-*'
          - 'caniuse-lite'
          - 'cssnano'
          - 'cssnano-*'
          - '*-loader'
          - 'postcss'
          - 'postcss-*'
          - 'sass-embedded'
          - 'webpack'
          - 'webpack-*'
          - '*-webpack-plugin'

      lint:
        patterns:
          - '@eslint/*'
          - '@trivago/prettier-plugin-*'
          - 'eslint'
          - 'eslint-*'
          - 'globals'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'typescript-*'

      test:
        patterns:
          - 'babel-jest'
          - 'jest'
          - 'jest-*'

      tools:
        patterns:
          - 'browser-sync'
          - 'concurrently'
          - 'del-cli'

    schedule:
      interval: monthly
    cooldown:
      default-days: 7

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

      # Include indirect browser data updates
      # https://web.dev/baseline
      - dependency-name: baseline-browser-mapping
      # https://caniuse.com
      - dependency-name: caniuse-lite

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Group actions into shared PR
    groups:
      actions:
        patterns:
          - '*'

    schedule:
      interval: monthly
    cooldown:
      default-days: 7
